added file reading and writing
Badyusha/AndersenCourses pull request #4
Opened 2024-12-27 18:23 UTC by Badyusha

2025-01-02 21:57 UTC, elnurmes approved these changes

2025-01-02 21:58 UTC, elnurmes commented
@Badyusha Custom exception missing

2025-01-02 21:59 UTC, elnurmes requested changes
missing custom exception

2025-01-02 22:46 UTC, Badyusha commented
hi, added custom exception

2025-01-03 09:33 UTC, elnurmes approved these changes

2025-01-03 11:25 UTC, merged